version: '3'
services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'test_db'   
      MYSQL_USER: 'test_user'
      MYSQL_PASSWORD: 'test_password'      
      MYSQL_ROOT_PASSWORD: 'test_password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './mysql-data/db:/var/lib/mysql'
      - './my.cnf:/etc/mysql/my.cnf'