version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - "./redis-data/redis:/data"
      - "./redis.conf/:/usr/local/etc/redis/redis.conf"